version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "notionrandomthought-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tf3ktxbg9lyv"
s3_prefix = "notionrandomthought-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
